permissions: Extend settings intelligence permissions.
java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG

Signed-off-by: spezi77 <spezi7713@gmx.net>